//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int ID_USER { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string LASTNAME { get; set; }
        public int ID_ROLE { get; set; }
        public string CODE { get; set; }
        public int PASSWORD { get; set; }
        public int ID_GENDER { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
